# swaylock — Catppuccin Mocha

# Colours (no #)
color=1e1e2e

inside-color=1e1e2e
inside-clear-color=1e1e2e
inside-ver-color=313244
inside-wrong-color=f38ba8

ring-color=cba6f7
ring-clear-color=a6e3a1
ring-ver-color=89b4fa
ring-wrong-color=f38ba8

key-hl-color=cba6f7
bs-hl-color=f38ba8

text-color=cdd6f4
text-clear-color=a6e3a1
text-ver-color=89b4fa
text-wrong-color=f38ba8

line-uses-ring
separator-color=00000000

# Layout
font=JetBrainsMono Nerd Font Bold
font-size=18
indicator-radius=100
indicator-thickness=10
ignore-empty-password
show-failed-attempts
daemonize
