# /etc/auto-cpufreq.conf
# Tuned for Intel i5-1035G1 laptop (8GB RAM)

[charger]
governor = performance
turbo = auto

[battery]
governor = powersave
energy_performance_preference = power
scaling_min_freq = 400000
scaling_max_freq = 3600000
turbo = auto
