#? Config file for btop v. 1.3.x

#* Name of a btop++/bpytop/bashtop formatted ".theme" file, "Default" and "TTY" for built-in themes.
color_theme = "catppuccin_mocha"

#* If the theme set background should be shown, set to False if you want terminal background transparency.
theme_background = True

#* Sets if 24-bit truecolor should be used, will convert 24-bit colors to 256 color (6x6x6 color cube) if false.
truecolor = True

#* Rounded corners on boxes, is not shown in TTY mode.
rounded_corners = True

#* Default symbols to use for graph creation, "braille", "block" or "tty".
graph_symbol = "braille"

#* Graph symbol to use for graphs in cpu box.
graph_symbol_cpu = "default"

#* Graph symbol to use for the net box graphs.
graph_symbol_net = "braille"

#* Graph symbol to use for the disk activity graphs.
graph_symbol_io = "braille"

#* Graph symbol to use for graphs in mem box.
graph_symbol_mem = "default"

#* Graph symbol to use for graphs in proc box.
graph_symbol_proc = "default"

#* Manually set which boxes to show. Available values are "cpu mem net proc" and "gpu0" through "gpu5".
shown_boxes = "cpu mem net proc"

#* Update time in milliseconds, recommended 2000 ms or above for better sample times for graphs.
update_ms = 2000

#* Processes sorting, "pid" "program" "arguments" "threads" "user" "memory" "cpu lazy" "cpu direct".
proc_sorting = "cpu lazy"

#* Reverse sorting order, True or False.
proc_reversed = False

#* Show processes as a tree.
proc_tree = False

#* Use the cpu graph colors in the process list.
proc_colors = True

#* Use a darkening gradient in the process list.
proc_gradient = True

#* If process cpu usage should be of the core it's running on or usage of the total available cpu power.
proc_per_core = False

#* Show process memory as bytes instead of percent.
proc_mem_bytes = True

#* Show cpu graph for each process.
proc_cpu_graphs = True

#* Use /proc/[pid]/smaps_rollup for mem information in the process list.
proc_info_smaps = False

#* Show proc box on left side of screen instead of right.
proc_left = False

#* Sets the CPU stat shown in upper half of the CPU graph: "total" "user" "system" or "nice".
cpu_graph_upper = "total"

#* Sets the CPU stat shown in lower half of the CPU graph: "total" "user" "system" or "nice".
cpu_graph_lower = "total"

#* Toggle enabling/disabling of cpu warning and alert.
cpu_warn_over = 80
cpu_crit_over = 95

#* Mem graphs size and mem box placement.
mem_graphs = True
mem_below_net = False
zfs_arc_cached = True

#* Set to true to swap the placement of the net box and the disk box.
net_auto = True
net_sync = False
net_iface = ""

#* Show battery stats in top right if battery is present.
show_battery = True

#* Offset to apply to displayed CPU temperatures.
temp_scale = "celsius"

#* Show temperatures for cpu cores in cpu box.
show_coretemp = True

#* Which sensor to use for cpu temp: "Auto", "coretemp", "acpitz" etc.
cpu_sensor = "Auto"

#* Show only physical cores (hyper-threading disabled).
only_physical = True

#* Show base clock-speed in the cpu graph, only available for Intel CPUs.
base_10_sizes = False

#* Show layout: "top" "bottom" horizontal scrollbar position.
show_disks = True
only_physical_disks = False
use_fstab = False
zfs_hide_datasets = False
disk_free_prct = False
io_mode = False
io_graph_speeds = {}
io_error_show = True

#* Disks to show in the disk box, set to "" for all.
disks_filter = ""

#* If swap memory should be shown in the mem box.
show_swap = True
swap_disk = True

#* If mem box should be split to also show mem info for /dev/shm.
show_shared_memory = True

log_level = "WARNING"
